import '../styles/globals.css';
import { Inter } from 'next/font/google';
import { AuthProvider } from './providers';
import Sidebar from '@/components/Sidebar';
// import { StoreProvider } from '../utils/Store';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <AuthProvider>{children}</AuthProvider>
//       </body>
//     </html>
//   );
// }

export default function Layout({ title, children }) {
  return (
    <html lang="en">
      <head>
        <title>
          {title ? title + ' - Icedout Fashion' : 'Icedout Fashion'}
        </title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>

      <body>
        <AuthProvider>
          <Sidebar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
